# This represents an orientation command for an aircraft in form of the Euler angles using the sequence 123 (XYZ). All angles are given in radians [rad] with respect to the
# aircraft frame (body axes).

# The roll angle (the orientation relative to the X axis).
float64 roll

# The pitch angle (the orientation relative to the Y axis).
float64 pitch

# The yaw angle (the orientation relative to the Z axis).
float64 yaw

# The thrust value for the aircraft measured in newtons.
float64 thrust